title: Crys-chelle Tate Tennyson, MBA # your name (or website title) here
logo: "/images/IMG_5221.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Analyzing data to change perspectives. <br><br>
  <img src="sunglasses4.png?raw=true"/>
  <a href="https://www.linkedin.com/in/cryschelletatetennyson/">View My LinkedIn Profile</a> 
  <img src="images/sunglasses4.png?raw=true"/>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
